version: "3.8"

services:
  web-search:
    image: registry.cn-hangzhou.aliyuncs.com/aasee-share/open-web-search:latest
    container_name: web-search
    working_dir: /app
    restart: no
    ports:
      - "3000:3000"
    command: ["node", "build/index.js"]
