version: "3.8"

services:
  web-search:
#    image: registry.cn-hangzhou.aliyuncs.com/aasee-share/open-web-search:latest # 国内
    image: ghcr.io/aas-ee/open-web-search:latest
    container_name: web-search
    working_dir: /app
    restart: no
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # DEFAULT_SEARCH_ENGINE: "duckduckgo" # default bing (optional)
      # USE_PROXY: true # Using a proxy (optional)
      # PROXY_URL: "xxx"  #  Using a proxy (optional)
      ENABLE_CORS: "true"
      CORS_ORIGIN: "*"  # Multiple values can be separated by commas and parsed accordingly | 可以多个值逗号分隔，自行解析
    command: ["node", "build/index.js"]
