version: "3.8"

services:
  web-search:
#    image: registry.cn-hangzhou.aliyuncs.com/aasee-share/open-web-search:latest # 国内
    image: ghcr.io/aas-ee/open-web-search:latest
    container_name: web-search
    working_dir: /app
    restart: no
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      ENABLE_CORS: "true"
      CORS_ORIGIN: "*"  # 可以多个值逗号分隔，自行解析
    command: ["node", "build/index.js"]
